const data = {
    prods: [
      {
        _id: '1',
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 500,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '2',
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 449,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '3',
        name: 'Lacoste Free Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 999,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '4',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 399,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '5',
        name: 'Puma Slim Pant',
        category: 'Pants',
        image: '/images/p5.jpg',
        price: 199,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '6',
        name: 'Adidas Fit Pant',
        category: 'Pants',
        image: '/images/p6.jpg',
        price: 249,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '7',
        name: 'Adidas Fit Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 399,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
      {
        _id: '8',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: 199,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product high quality product high quality product high quality product high quality product',
      },
    ],
  };
  export default data;